### ISSUE TITLE
Add SlidingCard with Fragment !

### ISSUE THREAD

**Issue by Noobknight** [mxn21/SlidingCard#2]
Hi ! :)
First, you've provided a library very useful and I'm thank for that ^^!
And you can support SlidingCard with Fragment ?

**Comment by mxn21** [comment]
you can use it in Fragment the same with in Activity.
do you mean this?

**Comment by Noobknight** [comment]
But.. when i use Fragment it not sliding cards...

**Comment by adavanayyappan** [comment]
class cast exception when using in fragment

**Comment by Noobknight** [comment]
@adavanayyappan Fix error it by change params in function initCardView to public void initCardView(final Fragment fragment,int layoutId,int rootId)
It work fine... But card not sliding !

**Comment by adavanayyappan** [comment]
thanks @Noobknight  you fix the error its working nicely

**Comment by mxn21** [comment]
do you put the SlidingCard in  listview or viewpager?

**Comment by adavanayyappan** [comment]
used in fragment oncreate view  thanks for nice tutorial

**Comment by Noobknight** [comment]
@adavanayyappan Working... But you can sliding cards ?

**Comment by mxn21** [comment]
@Noobknight if you put it in scrollable viewgroup like listview ,viewpager etc...sliding will not work .
Solution is don't use  'compile 'com.mxn.soul:slidingcard-core:1.2.0' ' and copy the library to your application. then see the Annotation


//    private ViewPager mPager;
//    private ListView listView;

//    public void setPagerAndListView(ViewPager mPager, ListView listView) {
//        this.mPager = mPager;
//        this.listView = listView;

//    @Override
//    public boolean dispatchTouchEvent(@NonNull MotionEvent ev) {
//        mPager.requestDisallowInterceptTouchEvent(true);
//        listView.requestDisallowInterceptTouchEvent(true);
//        return super.dispatchTouchEvent(ev);
//    }
//    @Override
//    public boolean onInterceptTouchEvent(MotionEvent ev) {
//        mPager.requestDisallowInterceptTouchEvent(true);
//        listView.requestDisallowInterceptTouchEvent(true);
//        return super.onInterceptTouchEvent(ev);
//    }
//    @Override
//    public boolean onTouchEvent(@NonNull MotionEvent event) {
//        mPager.requestDisallowInterceptTouchEvent(true);
//        listView.requestDisallowInterceptTouchEvent(true);
//        return super.onTouchEvent(event);
//    }

**Comment by Noobknight** [comment]
@mxn21 OK... I will try again :)

**Comment by adavanayyappan** [comment]
yes its  working  i can slide the cards @Noobknight

**Comment by Noobknight** [comment]
@adavanayyappan, @mxn21 working fine :)

**Comment by mxn21** [comment]
@Noobknight  ok
.

**Comment by adavanayyappan** [comment]
can i swipe cards vertically @mxn21

**Comment by mxn21** [comment]
@adavanayyappan  no ,sadly ， only drag horizontally so far

**Comment by adavanayyappan** [comment]
its ok thanks for your nice library @mxn21
